spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beeclub?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不需要统计的请求
      stat-view-servlet:
        login-username: root
        login-password: root
        
   
  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    #timeout: 0
    jedis:
      pool:
        max-wait: 1
        max-idle: 10
        max-active: 8
        min-idle: 5
        
  data:
    mongodb: 
      host: 127.0.0.1
      port: 27017
      database: beeclub
